sudo: false
language: perl
perl:
    - 'blead'
    - '5.26'
matrix:
    allow_failures:
        - perl: 'blead'
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
    - cpanm --quiet --skip-satisfied Path::Tiny
script:
    - make test
