language: perl
perl:
    - 'blead'
    - '5.30'
matrix:
    allow_failures:
        - perl: 'blead'
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
    - cpanm --quiet --skip-satisfied Code::TidyAll::Plugin::TestCount Path::Tiny Perl::Tidy Test::Code::TidyAll Test::Perl::Critic
script:
    - make test
